language: java

sudo: required
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - sh -e /etc/init.d/xvfb start
  - ./travis-tool.sh aptget_install r-cran-xml
  - sudo R CMD javareconf
  - ./travis-tool.sh install_github hadley/devtools
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package jimhester/covr
  - ./travis-tool.sh github_package trinker/entity
  - ./travis-tool.sh github_package trinker/syllable
  - ./travis-tool.sh github_package trinker/tagger
  - ./travis-tool.sh github_package trinker/formality
  - ./travis-tool.sh github_package trinker/gofastr
  - ./travis-tool.sh github_package trinker/lexr
  - ./travis-tool.sh github_package trinker/parsent
  - ./travis-tool.sh github_package trinker/qdapRegex
  - ./travis-tool.sh github_package trinker/readability
  - ./travis-tool.sh github_package trinker/sentimentr
  - ./travis-tool.sh github_package trinker/termco
  - ./travis-tool.sh github_package trinker/textproj
  - ./travis-tool.sh github_package trinker/textreadr
  - ./travis-tool.sh github_package trinker/textreport
  - ./travis-tool.sh github_package trinker/textshape
  - ./travis-tool.sh github_package trinker/stansent
script:      ./travis-tool.sh run_tests
after_success:
  - Rscript -e 'library(covr);coveralls()'
notifications:
  email:
    on_success:      change
    on_failure:      change
env:
   global:
     - R_BUILD_ARGS="--resave-data=best"
     - R_CHECK_ARGS="--as-cran"
     - DISPLAY=:99.0
     - BOOTSTRAP_LATEX=1
